// *******************************************************************************
// App

import { NgModule } from '@angular/core';

// *******************************************************************************

// TaigaUI

import {
//   TUI_SANITIZER,
//   TuiActiveZoneModule,
//   TuiAutoFocusModule,
//   TuiElementModule,
//   TuiFilterPipeModule,
  TuiLetModule,
//   TuiMapperPipeModule,
//   TuiMediaModule,
} from '@taiga-ui/cdk';
import {
    TuiButtonModule,
    // TuiCalendarModule,
    TuiDataListModule,
    // TuiDialogModule,
    // TuiDropdownControllerModule,
    // TuiDropdownModule,
    // TuiErrorModule,
    // TuiExpandModule,
    // TuiFormatNumberPipeModule,
    // TuiFormatPhonePipeModule,
    // TuiGroupModule,
    // TuiHintControllerModule,
    // TuiHintModule,
    // TuiHostedDropdownModule,
    // TuiLabelModule,
    // TuiLinkModule,
    // TuiLoaderModule,
    // TuiManualHintModule,
    // TuiModeModule,
    // TuiNotificationModule,
    // TuiNotificationsModule,
    // TuiPointerHintModule,
    // TuiPrimitiveCheckboxModule,
    // TuiPrimitiveTextfieldModule,
    // TuiRootModule,
    // TuiScrollbarModule,
    // TuiSvgModule,
    // TuiSvgService,
    // TuiTextfieldControllerModule,
    // TuiTooltipModule,
    // TuiAlertng addModule,
    TUI_BUTTON_OPTIONS,
  } from '@taiga-ui/core';
  import {
      TuiCarouselModule,
    TuiAccordionModule,
    // TuiActionModule,
    // TuiAvatarModule,
    // TuiBadgedContentModule,
    // TuiBadgeModule,
    // TuiBreadcrumbsModule,
    // TuiCalendarMonthModule,
    // TuiCalendarRangeModule,
    // TuiCheckboxBlockModule,
    // TuiCheckboxLabeledModule,
    // TuiCheckboxModule,
    // TuiComboBoxModule,
    TuiDataListWrapperModule,
    // TuiDropdownContextModule,
    // TuiDropdownSelectionModule,
    // TuiFieldErrorModule,
    // TuiFilterModule,
    // TuiHighlightModule,
    // TuiInputCopyModule,
    // TuiInputCountModule,
    // TuiInputDateModule,
    // TuiInputDateRangeModule,
    // TuiInputDateTimeModule,
    TuiInputFilesModule,
    // TuiInputInlineModule,
    // TuiInputModule,
    // TuiInputMonthModule,
    // TuiInputMonthRangeModule,
    // TuiInputNumberModule,
    // TuiInputPasswordModule,
    // TuiInputPhoneInternationalModule,
    // TuiInputPhoneModule,
    // TuiInputRangeModule,
    // TuiInputSliderModule,
    // TuiInputTagModule,
    // TuiInputTimeModule,
    TuiIslandModule,
    // TuiLazyLoadingModule,
    // TuiLineClampModule,
    // TuiMarkerIconModule,
    TuiMultiSelectModule,
    // TuiPaginationModule,
    // TuiPresentModule,
    // TuiProgressModule,
    // TuiProjectClassModule,
    // TuiFilterByInputPipeModule,
    // TuiRadioBlockModule,
    // TuiRadioLabeledModule,
    // TuiRadioListModule,
    // TuiRadioModule,
    // TuiSelectModule,
    // TuiSliderModule,
    // TuiStepperModule,
    TuiTabsModule,
    // TuiTagModule,
    // TuiTextAreaModule,
    // TuiToggleModule,
      TuiRangeModule,
      // TuiAlertModule
  } from '@taiga-ui/kit';

  import * as icons from '@taiga-ui/icons';

  // import {TuiColorPickerModule, TuiEditorModule, TuiEditorSocketModule} from '@taiga-ui/addon-editor';
  // import {
  //   // TuiReorderModule,
  //   // TuiResizableColumnModule,
  //   // TuiTablePaginationModule,
  //   // TuiTableModule,
  // } from '@taiga-ui/addon-table';



  // *******************************************************************************



@NgModule({
    imports: [
      TuiAccordionModule,
    //   TuiActionModule,
    //   TuiActiveZoneModule,
    //   TuiAvatarModule,
    //   TuiBadgeModule,
    //   TuiBadgedContentModule,
      TuiButtonModule,
        TuiCarouselModule,
    //   TuiCalendarModule,
    //   TuiCalendarRangeModule,
    //   TuiCalendarMonthModule,
    //   TuiCardModule,
    //   TuiAxesModule,
    //   TuiLineChartModule,
    //   TuiLineDaysChartModule,
    //   TuiPieChartModule,
    //   TuiBarChartModule,
    //   TuiRingChartModule,
    //   TuiCheckboxModule,
    //   TuiCheckboxBlockModule,
    //   TuiCheckboxLabeledModule,
    //   TuiPrimitiveCheckboxModule,
    //   TuiColorPickerModule,
      TuiDataListModule,
      TuiDataListWrapperModule,
    //   TuiDropdownContextModule,
    //   TuiHostedDropdownModule,
    //   TuiErrorModule,
    //   TuiEditorModule,
    //   TuiEditorSocketModule,
    //   TuiExpandModule,
    //   TuiFieldErrorModule,
    //   TuiFilterModule,
    //   TuiGroupModule,
    //   TuiMarkerIconModule,
    //   TuiInputInlineModule,
    //   TuiInputModule,
    //   TuiInputDateModule,
    //   TuiInputCardModule,
    //   TuiInputCVCModule,
    //   TuiInputExpireModule,
    //   TuiInputCopyModule,
    //   TuiInputCountModule,
    //   TuiInputDateTimeModule,
      TuiInputFilesModule,
    //   TuiInputMonthModule,
    //   TuiInputMonthRangeModule,
    //   TuiInputNumberModule,
    //   TuiInputPasswordModule,
    //   TuiInputPhoneModule,
    //   TuiInputRangeModule,
    //   TuiInputDateRangeModule,
    //   TuiInputSliderModule,
    //   TuiInputTagModule,
    //   TuiInputTimeModule,
    //   TuiInputPhoneInternationalModule,
    //   TuiPrimitiveTextfieldModule,
    //   TuiTextAreaModule,
      TuiIslandModule,
    //   TuiLabelModule,
    //   TuiLineClampModule,
    //   TuiLinkModule,
    //   TuiLoaderModule,
    //   TuiMoneyModule,
    //   TuiNotificationModule,
    //   TuiMobileDialogModule,
    //   TuiMobileCalendarModule,
    //   TuiPullToRefreshModule,
    //   TuiRadioModule,
    //   TuiRadioBlockModule,
    //   TuiRadioLabeledModule,
    //   TuiRadioListModule,
    //   TuiComboBoxModule,
      TuiMultiSelectModule,
    //   TuiSelectModule,
    //   TuiScrollbarModule,
    //   TuiInputRangeModule,
    //   TuiInputSliderModule,
    //   TuiSliderModule,
    //   TuiSvgModule,
    //   TuiReorderModule,
    //   TuiResizableColumnModule,
    //   TuiTablePaginationModule,
    //   TuiTagModule,
    //   TuiToggleModule,
    //   TuiTooltipModule,
    //   TuiBreadcrumbsModule,
    //   TuiPaginationModule,
    //   TuiStepperModule,
      TuiTabsModule,
    //   TuiAutoFocusModule,
    //   TuiDropdownModule,
    //   TuiDropdownSelectionModule,
    //   TuiElasticStickyModule,
    //   TuiElementModule,
    //   TuiHighlightModule,
    //   TuiHintModule,
    //   TuiLazyLoadingModule,
    //   TuiManualHintModule,
    //   TuiPointerHintModule,
      TuiLetModule,
    //   TuiMediaModule,
    //   TuiModeModule,
    //   TuiPresentModule,
    //   TuiProgressModule,
    //   TuiRippleModule,
    //   TuiSidebarModule,
    //   TuiDropdownControllerModule,
    //   TuiTouchableModule,
    //   TuiHintControllerModule,
    //   TuiTextfieldControllerModule,
    //   TuiMoneyModule,
    //   // PolymorpheusModule,
    //   TuiFilterPipeModule,
    //   TuiFormatNumberPipeModule,
    //   TuiFormatPhonePipeModule,
    //   TuiMapperPipeModule,
    //   TuiTableModule,
    //   TuiBarModule,
    //   TuiCurrencyPipeModule,
    //   TuiProjectClassModule,
    //   TuiFilterByInputPipeModule,
        TuiRangeModule
    ],

    exports: [
          TuiAccordionModule,
        //   TuiActionModule,
        //   TuiActiveZoneModule,
        //   TuiAvatarModule,
        //   TuiBadgeModule,
        //   TuiBadgedContentModule,
          TuiButtonModule,
        TuiCarouselModule,
        //   TuiCalendarModule,
        //   TuiCalendarRangeModule,
        //   TuiCalendarMonthModule,
        //   TuiCardModule,
        //   TuiAxesModule,
        //   TuiLineChartModule,
        //   TuiLineDaysChartModule,
        //   TuiPieChartModule,
        //   TuiBarChartModule,
        //   TuiRingChartModule,
        //   TuiCheckboxModule,
        //   TuiCheckboxBlockModule,
        //   TuiCheckboxLabeledModule,
        //   TuiPrimitiveCheckboxModule,
        //   TuiColorPickerModule,
          TuiDataListModule,
          TuiDataListWrapperModule,
        //   TuiDropdownContextModule,
        //   TuiHostedDropdownModule,
        //   TuiErrorModule,
        //   TuiEditorModule,
        //   TuiEditorSocketModule,
        //   TuiExpandModule,
        //   TuiFieldErrorModule,
        //   TuiFilterModule,
        //   TuiGroupModule,
        //   TuiMarkerIconModule,
        //   TuiInputInlineModule,
        //   TuiInputModule,
        //   TuiInputDateModule,
        //   TuiInputCardModule,
        //   TuiInputCVCModule,
        //   TuiInputExpireModule,
        //   TuiInputCopyModule,
        //   TuiInputCountModule,
        //   TuiInputDateTimeModule,
          TuiInputFilesModule,
        //   TuiInputMonthModule,
        //   TuiInputMonthRangeModule,
        //   TuiInputNumberModule,
        //   TuiInputPasswordModule,
        //   TuiInputPhoneModule,
        //   TuiInputRangeModule,
        //   TuiInputDateRangeModule,
        //   TuiInputSliderModule,
        //   TuiInputTagModule,
        //   TuiInputTimeModule,
        //   TuiInputPhoneInternationalModule,
        //   TuiPrimitiveTextfieldModule,
        //   TuiTextAreaModule,
          TuiIslandModule,
        //   TuiLabelModule,
        //   TuiLineClampModule,
        //   TuiLinkModule,
        //   TuiLoaderModule,
        //   TuiMoneyModule,
        //   TuiNotificationModule,
        //   TuiMobileDialogModule,
        //   TuiMobileCalendarModule,
        //   TuiPullToRefreshModule,
        //   TuiRadioModule,
        //   TuiRadioBlockModule,
        //   TuiRadioLabeledModule,
        //   TuiRadioListModule,
        //   TuiComboBoxModule,
          TuiMultiSelectModule,
        //   TuiSelectModule,
        //   TuiScrollbarModule,
        //   TuiInputRangeModule,
        //   TuiInputSliderModule,
        //   TuiSliderModule,
        //   TuiSvgModule,
        //   TuiReorderModule,
        //   TuiResizableColumnModule,
        //   TuiTablePaginationModule,
        //   TuiTagModule,
        //   TuiToggleModule,
        //   TuiTooltipModule,
        //   TuiBreadcrumbsModule,
        //   TuiPaginationModule,
        //   TuiStepperModule,
          TuiTabsModule,
        //   TuiAutoFocusModule,
        //   TuiDropdownModule,
        //   TuiDropdownSelectionModule,
        //   TuiElasticStickyModule,
        //   TuiElementModule,
        //   TuiHighlightModule,
        //   TuiHintModule,
        //   TuiLazyLoadingModule,
        //   TuiManualHintModule,
        //   TuiPointerHintModule,
          TuiLetModule,
        //   TuiMediaModule,
        //   TuiModeModule,
        //   TuiPresentModule,
        //   TuiProgressModule,
        //   TuiRippleModule,
        //   TuiSidebarModule,
        //   TuiDropdownControllerModule,
        //   TuiTouchableModule,
        //   TuiHintControllerModule,
        //   TuiTextfieldControllerModule,
        //   TuiMoneyModule,
        //   // PolymorpheusModule,
        //   TuiFilterPipeModule,
        //   TuiFormatNumberPipeModule,
        //   TuiFormatPhonePipeModule,
        //   TuiMapperPipeModule,
        //   TuiTableModule,
        //   TuiBarModule,
        //   TuiCurrencyPipeModule,
        //   TuiProjectClassModule,
        //   TuiFilterByInputPipeModule,
        TuiRangeModule
    ],

    providers: [
      // {
      //   provide: TUI_BUTTON_OPTIONS,
      //   useValue: {
      //       // appearance: 'flat',
      //       // itemSize: 'm',
      //       // shape: 'rounded'
      //   },
    // },
    ],

  })
  export class TaigaUIModule {}

